"""
Phase 5: Report Generator — Compiles the validated research into a clean
final report with executive summary, findings, confidence ratings, and sources.
"""


def _build_report_prompt(topic: str, profile: str, history: list,
                         validation_result: str, challenge_result: str,
                         total_rounds: int) -> str:
    """Build the prompt for final report generation."""
    history_text = ""
    for h in history:
        history_text += f"\n### Round {h['round']}\n"
        history_text += f"- Improvements found: {h['improvement_count']}\n"
        if h.get('improvement_points'):
            for p in h['improvement_points'][:5]:
                history_text += f"  - {p}\n"
        history_text += f"- Validation: {h.get('validation_summary', 'N/A')[:200]}\n"
        history_text += f"- Challenge: {h.get('challenge_summary', 'N/A')[:200]}\n"

    return f"""You are a RESEARCH REPORT WRITER. Your job is to take a validated Research Profile
and compile it into a professional, publication-ready final report.

TOPIC: {topic}
ADVERSARIAL ROUNDS COMPLETED: {total_rounds}

VALIDATED RESEARCH PROFILE:
{profile[:12000]}

ADVERSARIAL HISTORY:
{history_text}

LATEST VALIDATION:
{validation_result[:3000]}

LATEST CHALLENGE:
{challenge_result[:3000]}

YOUR MISSION:
Create a polished final report that:
1. Synthesizes everything into a clear, readable narrative
2. Shows confidence levels for each major finding
3. Acknowledges what survived adversarial scrutiny and what didn't
4. Cites sources properly
5. Is accessible to a non-expert audience

OUTPUT FORMAT:

# Final Research Report: {topic}

## Executive Summary
2-3 paragraph overview of key findings and their confidence levels.

## Key Findings

### Finding 1: [Title]
- **What we found:** [clear statement]
- **Evidence strength:** [Strong/Moderate/Weak] ★★★★☆
- **Sources:** [key sources]
- **Adversarial testing:** [how this survived validation/challenge]

### Finding 2: [Title]
[repeat format]

[Continue for all significant findings]

## Data & Statistics
Key numbers and metrics with sources.

## What Changed Through Adversarial Testing
Brief summary of how the research evolved:
- Round 1: What was challenged and how it was addressed
- Round 2: [if applicable]
- Round 3: [if applicable]

## Remaining Uncertainties
Honest assessment of what we still don't know or can't verify.

## Sources
Complete bibliography with URLs.

## Methodology Note
Brief description of the adversarial research process used.

---
*This report survived {total_rounds} rounds of adversarial interrogation.
Generated by No-Slop Research.*"""


class ReportGenerator:
    """Generates the final research report."""

    def generate(self, topic: str, profile: str, history: list,
                 validation_result: str, challenge_result: str,
                 total_rounds: int) -> str:
        """
        Generate the final report from validated research.
        Returns formatted report.
        """
        prompt = _build_report_prompt(
            topic=topic,
            profile=profile,
            history=history,
            validation_result=validation_result,
            challenge_result=challenge_result,
            total_rounds=total_rounds
        )

        # The Hermes skill executes this as a subagent
        # In standalone mode, return the prompt
        return prompt

    def generate_markdown(self, topic: str, profile: str, history: list,
                         validation_result: str, challenge_result: str,
                         total_rounds: int) -> str:
        """
        Generate report and format as clean markdown.
        When called from Hermes with subagent results, pass the result here.
        """
        report = self.generate(topic, profile, history, validation_result,
                              challenge_result, total_rounds)
        return report

    def extract_findings_summary(self, report: str) -> dict:
        """
        Extract a structured summary of findings from the final report.
        """
        import re
        findings = []

        # Find all "### Finding N:" sections
        finding_pattern = r'### Finding \d+:\s*(.+?)(?=### Finding|\n## |\Z)'
        matches = re.findall(finding_pattern, report, re.DOTALL)

        for match in matches:
            lines = match.strip().split("\n")
            title = lines[0].strip()
            evidence = "unknown"
            for line in lines:
                if "evidence strength" in line.lower():
                    if "strong" in line.lower():
                        evidence = "strong"
                    elif "moderate" in line.lower():
                        evidence = "moderate"
                    elif "weak" in line.lower():
                        evidence = "weak"
            findings.append({"title": title, "evidence": evidence})

        return {
            "total_findings": len(findings),
            "strong": sum(1 for f in findings if f["evidence"] == "strong"),
            "moderate": sum(1 for f in findings if f["evidence"] == "moderate"),
            "weak": sum(1 for f in findings if f["evidence"] == "weak"),
            "findings": findings
        }
